- name: Update packages
  tags: update-packages
  become: true
  block:
    - name: Update all packages (Debian)
      tags: skip_ansible_lint
      ansible.builtin.apt:
        upgrade: full
        update_cache: true
        cache_valid_time: 3600
      when: ansible_os_family == "Debian"

    - name: Update all packages (RedHat)
      tags: skip_ansible_lint
      ansible.builtin.dnf:
        name: "*"
        state: latest
        update_cache: true
      when: ansible_os_family == "RedHat"

    - name: Update all packages (ArchLinux)
      tags: skip_ansible_lint
      community.general.pacman:
        update_cache: true
        upgrade: true
      when: ansible_os_family == "Archlinux"
