version: "3.9"

services:
  quark:
    container_name: quark
    build:
      context: .
      dockerfile: quark.dockerfile
    ports:
      - "3000:8080"
    volumes:
      - ./assets/index.html:/var/www/html/index.html
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080"]
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s

  reverse-proxy:
    build:
      context: .
      dockerfile: reverse-proxy.dockerfile
    volumes:
      - ./assets/nginx.conf:/tmp/nginx.conf
    ports:
      - "81:81"
    environment:
      - PROXY_PASS=http://quark:8080
      - PORT=81
      - SERVER_NAME=localhost
    depends_on:
      quark:
        condition: service_healthy
