- name: Installer msmtp
  become: true
  tags:
    - msmtp
    - msmtp-install
  ansible.builtin.package:
    name: msmtp
    state: present

- name: Configurer msmtp
  become: true
  tags:
    - msmtp
    - msmtp-config
  ansible.builtin.template:
    src: config.j2
    dest: /etc/msmtprc
    owner: root
    group: root
    mode: "0644"
